New person
theopensource-company/website pull request #12
Opened 2022-10-17 11:45 UTC by Hesselaar23

Added Hessel van Bakel to the team

2022-10-17 13:17 UTC, kearfy commented
Currently it will show Ties's picture for the new profile

2022-10-17 13:26 UTC, kearfy requested changes
Currently it will show Ties's picture for the new profile

2022-10-18 09:02 UTC, Hesselaar23 commented
fixed the easy fuck up

2022-10-20 18:10 UTC, kearfy approved these changes

2022-10-20 18:10 UTC, merged